apiVersion: apps/v1
kind: Deployment
metadata:
  name: sac-app
  namespace: grupoguma
  labels:
    app: sac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sac-app
  template:
    metadata:
      labels:
        app: sac-app
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cn-sac-app
          image: gumadesarrollo/sac:v1.2.{{BUILD_NUMBER}}
          imagePullPolicy: Always
          volumeMounts:
            - name: storage
              mountPath: /data/web/storage
              subPath: storageApp
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
              name: laravel-config
          env:
            - name: APP_KEY
              value: base64:tYaI3cGTEA3iFoXnqyzBh3yx2eTDKKGvPjWd7f20NQA=
          resources:
            requests:
              memory: "64Mi"
              cpu: "72m"
            limits:
              memory: "128Mi"
              cpu: "144m"
