apiVersion: v1
kind: Service
metadata:  
  name: sac-svc 
  namespace: grupoguma
spec:
  selector:    
    app: sac-app
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000